# Generated by Django 5.1.7 on 2025-07-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adausdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adausdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aptusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aptusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaxusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaxusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bchusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bchusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bnbusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bnbusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btcusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btcusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogeusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogeusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dotusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ethusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ethusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icpusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icpusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ltcusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ltcusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maticusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maticusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shibusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shibusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tonusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tonusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xlmusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xlmusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrpusdtdetail',
            name='percent_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrpusdtdetail',
            name='percent_change_7d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
