# Generated by Django 5.1.7 on 2025-07-14 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adausdtdetail_percent_change_24h_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adausdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='aptusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='avaxusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='bchusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='bnbusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='btcusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='dogeusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='dotusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='ethusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='icpusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='linkusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='ltcusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='maticusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='nearusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='shibusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='solusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='tonusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='uniusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='xlmusdtdetail',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='xrpusdtdetail',
            name='percent_change_7d',
        ),
    ]
